name: 💡 General Feature Request
description: Suggest features, propose improvements, and discuss new ideas!
title: "[FEATURE] <description>"
labels: ["enhancement", "🚦 awaiting triage"]

body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe the enhancement you propose, including what you tried and what worked.
      placeholder: "Example: 'When I try to upload large files (over 100MB), the process succeeds but takes more than 10 minutes. This disrupts my workflow and causes delays in my project.'"
    validations:
      required: true
  
  - type: textarea
    id: tech-notes
    attributes:
      label: Tech notes
      description: Please add any tech notes related to this feature request
      placeholder: "Add some technical details to implement this feature if you already know how to deal with it, or just skip this section."
    validations:
      required: false
  
  - type: textarea
    id: attachments
    attributes:
      label: Screenshots or Diagrams
      description: Add screenshots or diagrams to help us understand the feature request.
      placeholder: "Attach it here"
    validations:
      required: false
  
  - type: textarea
    id: extra-info
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
      placeholder: "Describe it here"
    validations:
      required: false
