name: 💡 General Feature Request
description: Suggest features, propose improvements, and discuss new ideas!
title: "[FEATURE] <description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose, also including what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: tech-notes
    attributes:
      label: Tech notes
      description: Please add any tech notes related to this feature request
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
